version: '3'  
 
services: 


  mosquitto:
    image: eclipse-mosquitto
    user: 1001:1001
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto-data/mosquitto.conf:/mosquitto/config/mosquitto.conf 
    

  panduza-platform: 
    image: ghcr.io/panduza/panduza-py-platform:latest
    user: 1001:1001
    network_mode: host
    volumes:
      - ../..:/workdir/panduza-py-platform
      - ./panduza-data/tree.json:/etc/panduza/tree.json
    command: python3 /workdir/panduza-py-platform/deploy/pza-py-platform-run.py

